In [7]:
import math
import numpy as np
mysinh = math.sinh(1)
 

In [44]:
def mysinH(x):
    return round((np.exp(x)-np.exp(-x))/2,4)

In [13]:
print(round(
    mysinH(0), 4))
print(round(
    mysinH(1), 4))

round(mysinH(2), 4)

0.0
1.1752


3.6269

In [55]:
def my_checker_board(x, y):
    my_checker_board = np.zeros((x,y),dtype=int)
    my_checker_board[::2,::2] = 1
    return my_checker_board

print(f' my check board: \n {my_checker_board(3,5)} \n \t my second check board: {my_checker_board(1,1)} and \n {mysinH(5)}')


 my check board: 
 [[1 0 1 0 1]
 [0 0 0 0 0]
 [1 0 1 0 1]] 
 	 my second check board: [[1]] and 
 74.2032


In [40]:
t = my_checker_board(2,5)
t

array([[1, 0, 1, 0, 1],
       [0, 0, 0, 0, 0]])

In [45]:
t = mysinH(3)
t

10.0179

In [56]:
def my_split_matrix(m):
    n = len(m[0])
    if n % 2 == 0:
        return [m[:, :n//2], m[:, n//2:]]
    else:
        return [m[:, :(n+1)//2], m[:, (n+1)//2:]]


In [64]:

r = np.arange(36).reshape(4,9)

my_split_matrix(r)

[array([[ 0,  1,  2,  3,  4],
        [ 9, 10, 11, 12, 13],
        [18, 19, 20, 21, 22],
        [27, 28, 29, 30, 31]]),
 array([[ 5,  6,  7,  8],
        [14, 15, 16, 17],
        [23, 24, 25, 26],
        [32, 33, 34, 35]])]

In [65]:
def my_checker_board(n):
    return np.tile([1, 0], n//2+1)[:n]


In [71]:
my_checker_board(8)

array([1, 0, 1, 0, 1, 0, 1, 0])

In [75]:
j = lambda x, y: x - y

In [78]:
print(j(1
        ,3))


-2


In [82]:
sorted([(2,1), (4,6), (8,0), (1,2), (3,1), (5,4), (7,2), (9,0)], key= lambda x: x[0]
       )

[(1, 2), (2, 1), (3, 1), (4, 6), (5, 4), (7, 2), (8, 0), (9, 0)]

In [83]:
add_strings = lambda x, y: x + y
add_strings('hello', ' world')

'hello world'

In [84]:
s1 = add_strings('Programming', ' ')
s2 = add_strings('is', ' fun!')
add_strings(s1, s2)

'Programming is fun!'

In [90]:
def greeting(name, age):
    return f'My name is {name} and I am {age} years old.'
name = 'Akorede'
age = 28
korede = greeting('Akorede', 27)
korede

'My name is Akorede and I am 27 years old.'

In [91]:
fog = np.arange(1,4)

In [92]:
fog

array([1, 2, 3])

In [110]:
def my_donut_area(r1, r2):
    return [np.pi *(r2)**2- np.pi *(r1)**2, 4]
    

my_donut_area(np.arange(1, 4), np.arange(2, 7, 2))

[array([ 9.42477796, 37.69911184, 84.82300165]), 4]

In [125]:
def my_within_tolerance(A, a, tol):
    return np.where(np.abs(A - a) < tol)[0]

#help(np.where)
my_within_tolerance(np.array([0, 1, 2, 3]), 1.5, 0.75)

array([1, 2], dtype=int64)

In [128]:
def bounding_array(A, top, bottom):
    return [np.where(A < bottom, bottom, np.where(A > top, top, A))]

bounding_array(np.arange(-5, 6, 1), 3, -3)


[array([-3, -3, -3, -2, -1,  0,  1,  2,  3,  3,  3])]

In [129]:
erg = np.arange(-5, 7, 1)
erg

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6])

In [130]:
import requests

In [133]:
get = requests.get('https://www.youtube.com/watch?v=CiGBhVCe9DA&list=PPSV')
get

<Response [200]>